# Generated by Django 4.2.25 on 2025-11-05 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('sku', models.CharField(max_length=128)),
                ('warehouse', models.CharField(max_length=64)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=128)),
                ('warehouse', models.CharField(max_length=64)),
                ('qty', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('released', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('RESERVE', 'RESERVE'), ('RELEASE', 'RELEASE'), ('SHIP', 'SHIP'), ('ADJUST', 'ADJUST')], max_length=16)),
                ('qty', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['sku'], name='inventory_i_sku_78cea7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse'], name='inventory_i_warehou_5c1dcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('sku', 'warehouse')},
        ),
    ]
